If:
  PathMatch: .*\.(cpp|cxx|cc|h|hpp)
CompileFlags:
  Add:
    - "-std=c++23"
    - "-Wall"
    - "-Wextra"
---
If:
  PathMatch: .*\.c
CompileFlags:
  Add:
    - "-std=c17"
    - "-Wall"
    - "-Wextra"
---
Index:
  Background: Build
